As a CMR Operator, I want all necessary evaluation metrics to be logged, so I have visibility into system performance.
cmr-exchange/cmr-sizing-plugin pull request #9
Opened 2018-11-14 18:43 UTC by daniel-zamora

This PR adds a UUID request id, and logs any relevant data used in the size estimation calculation, the format estimate (prior to spatial) then the final estimate, and the elapsed duration.

2018-11-15 15:42 UTC, chris-durbin approved these changes

2018-11-15 15:42 UTC, chris-durbin commented on src/cmr/sizing/app/handler.clj
> +          request-id (str (java.util.UUID/randomUUID))
I think our standard is to:
```
(:import
 (java.util UUID)
...
(UUID/randomUUID)
```

2018-11-15 16:00 UTC, oubiwann requested changes
Okay, this looks great; the only thing that needs to be changed is where the request-id is set -- that needs to be done in another dep (linked in comment). That will get merged (with a bump to the micro-version, for Nexus' sake!)

2018-11-15 16:00 UTC, oubiwann commented on src/cmr/sizing/formats.clj
> +    (log/info (format "request-id: %s metadata: %s compression: %s measurements: %s"
I suspect we'll want this to be `log/debug` ... since that really what it's going to be used for (well, double-checking the implementation, accuracy, and debugging). Once the initial dev phase is complete and this work is considered done/good enough, I can't foresee ever using this at an INFO level ...

But! all that is just for _your_ info ;-) We can change later, as needed.

2018-11-15 16:00 UTC, oubiwann commented on src/cmr/sizing/app/handler.clj
> +          request-id (str (java.util.UUID/randomUUID))
We do definitely want to double-check our usage here; I did some searching online to back up my own personal experiences, and there are VERY widely varying accounts of excellent-to-extremely-poor UUID performance ...

2018-11-15 16:00 UTC, oubiwann commented on src/cmr/sizing/app/handler.clj
> +          request-id (str (java.util.UUID/randomUUID))
Also, we probably want to add the request-id in middleware, so all requests in service-bridge benefit from this:
* Take a look at https://github.com/cmr-exchange/cmr-http-kit/blob/master/src/cmr/http/kit/app/middleware.clj
* Create `wrap-request-id` a la some of the other simple request wrappers there
* Update `wrap-ring-middleware` at the bottom of the file to include `wrap-request-id` at the top of the stack, right before `wrap-log-request`.

2018-11-15 16:00 UTC, oubiwann commented on src/cmr/sizing/formats.clj
> +                      (:request-id params) compression measurements))
Oh, good -- you added this. Didn't see this at first and was getting ready to make a request that you do :-)

2018-11-16 16:18 UTC, daniel-zamora commented on src/cmr/sizing/core.clj
> +                             :request-id (:request-id raw-params))
this can probably be removed.

2018-11-16 16:36 UTC, oubiwann approved these changes

2018-11-16 16:39 UTC, merged